security:
    encoders:
        DrutaBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

    role_hierarchy:
        ROLE_ADMIN: [ROLE_ADMIN]

    providers:
        user_db:
            entity: { class: DrutaBundle\Entity\User, property: username }

    firewalls:
        main:
            pattern: ^/
            provider: user_db
            form_login:
                login_path: /
                check_path: /login_check
                remember_me: true
                always_use_default_target_path: true
                default_target_path: /user/dashboard
            logout:
                path: /logout
                target: /
            remember_me:
                key: MiClaveSegura
                lifetime: 1800
                path: /.*
                domain: ~
            security: true
            anonymous: ~

    access_control:
        - { path: ^/open, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
    # Estrategia de voters (por defecto affirmative)
    access_decision_manager:
        strategy: unanimous
